### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by 0xthc** [socialement-competents/hackafront#5]
add `.nvmrc` file

**Comment by tsauvajon** [comment]
C'est quoi

**Comment by 0xthc** [comment]
Nvm c’est un node version manager ça permet de switch entre les versions de node, et du coup quand dans ton projet t’as un .nvmrc qui contient juste la version de node genre 6.11.3 ou 7.6.0 t’as juste à faire nvm use pour avoir la bonne version de node

**Comment by tsauvajon** [comment]
Ah OK habile je connaissais pas
