### ISSUE TITLE
Push l'image Docker uniquement lors d'un tag

### ISSUE THREAD

**Issue by tsauvajon** [socialement-competents/hackafront#6]
Quand on sera rodés, il faudrait push l'image Docker uniquement lorsqu'on `git tag` pour éviter les images inutiles + avoir des tags d'image Docker utiles et faciles à utiliser.

**Comment by 0xthc** [comment]
Normalement on est censé créer un tag à chaque build pr/ master pour pouvoir run les tests dans un contexte spécifique mais j'sais pas le nbre d'images/ tags qu'on peut avoir sur le registry

**Comment by tsauvajon** [comment]
Plutôt à chaque release qu'à chaque build.
Edit : en lisant j'avais mal compris en fait !
